"use strict"

export const view = {
  elements: {
    body: document.body,
    mainContents: document.getElementById("mainContents"),
    aside: document.querySelector("aside"),
    main: document.querySelector("main"),
    expandbutton: document.getElementById("expandbutton"),
    map: document.getElementById("map"),
    markdownText: document.getElementById("markdownText"),
    markdown: document.getElementById("markdown"),
    markdownArea: document.getElementById("markdownArea"),
    registerbutton: document.getElementById("registerbutton"),
    markdownHeader: document.getElementById("markdownHeader"),
    longlat: document.forms.longlat,
    markdownInput: document.forms.markdownInput,
    delete: document.getElementById("delete"),
    post: document.getElementById("post"),
    close: document.getElementById("close"),
    positionPlot: document.getElementById("positionPlot"),
    positionLongitude: document.forms.position.longitude,
    positionLatitude: document.forms.position.latitude,
    longlatLongitude: document.forms.longlat.longitude,
    longlatLatitude: document.forms.longlat.latitude,
    title: document.forms.markdownInput.title,
    keywords: document.forms.markdownInput.keywords,
    wiki: document.getElementById("wiki"),
    wikiTitle : document.getElementById("wikiTitle"),
    wikiHTML : document.getElementById("wikiHTML"),
    fullscreen: document.getElementById("fullscreenIcon"),
    edit: document.getElementById("editIcon"),
    fullscreenMode: document.getElementById("fullscreenMode"),
    fullscreenTitle: document.getElementById("fullscreenTitle"),
    fullscreenSection: document.getElementById("fullscreenSection"),
    close2: document.getElementById("close2"),
  }
}
